package com.example.kairos;

import java.util.Arrays;
import java.util.List;

public final class CountryCityData_Africa implements CountryCityData {
    @Override public List<Country> countries() { return Arrays.asList(
            new Country("DZ","Algeria", Arrays.asList("Algiers","Oran","Constantine","Annaba","Tlemcen")),
            new Country("AO","Angola", Arrays.asList("Luanda","Benguela","Huambo","Lubango","Lobito")),
            new Country("BJ","Benin", Arrays.asList("Cotonou","Porto-Novo","Abomey","Parakou","Ouidah")),
            new Country("BW","Botswana", Arrays.asList("Gaborone","Francistown","Maun","Kasane","Molepolole")),
            new Country("BF","Burkina Faso", Arrays.asList("Ouagadougou","Bobo-Dioulasso","Koudougou","Banfora","Ouahigouya")),
            new Country("BI","Burundi", Arrays.asList("Bujumbura","Gitega","Ngozi","Rumonge","Makamba")),
            new Country("CV","Cabo Verde", Arrays.asList("Praia","Mindelo","Santa Maria","Espargos","Assomada")),
            new Country("CM","Cameroon", Arrays.asList("Yaoundé","Douala","Bafoussam","Limbe","Garoua")),
            new Country("CF","Central African Republic", Arrays.asList("Bangui","Berbérati","Bambari","Bouar","Bria")),
            new Country("TD","Chad", Arrays.asList("N'Djamena","Moundou","Abéché","Sarh","Koumra")),
            new Country("KM","Comoros", Arrays.asList("Moroni","Mutsamudu","Fomboni","Iconi","Domoni")),
            new Country("CD","Congo (DRC)", Arrays.asList("Kinshasa","Lubumbashi","Goma","Kisangani","Bukavu")),
            new Country("CG","Congo (Republic)", Arrays.asList("Brazzaville","Pointe-Noire","Dolisie","Owando","Oyo")),
            new Country("CI","Côte d'Ivoire", Arrays.asList("Abidjan","Yamoussoukro","Bouaké","San-Pédro","Man")),
            new Country("DJ","Djibouti", Arrays.asList("Djibouti","Ali Sabieh","Tadjourah","Obock","Arta")),
            new Country("EG","Egypt", Arrays.asList("Cairo","Giza","Alexandria","Luxor","Aswan")),
            new Country("GQ","Equatorial Guinea", Arrays.asList("Malabo","Bata","Mongomo","Ebebiyín","Luba")),
            new Country("ER","Eritrea", Arrays.asList("Asmara","Massawa","Keren","Assab","Mendefera")),
            new Country("SZ","Eswatini", Arrays.asList("Mbabane","Manzini","Lobamba","Siteki","Pigg's Peak")),
            new Country("ET","Ethiopia", Arrays.asList("Addis Ababa","Gondar","Mekelle","Hawassa","Dire Dawa")),
            new Country("GA","Gabon", Arrays.asList("Libreville","Port-Gentil","Franceville","Oyem","Lambaréné")),
            new Country("GM","Gambia", Arrays.asList("Banjul","Serrekunda","Bakau","Brikama","Farafenni")),
            new Country("GH","Ghana", Arrays.asList("Accra","Kumasi","Takoradi","Tamale","Cape Coast")),
            new Country("GN","Guinea", Arrays.asList("Conakry","Kindia","Labé","Kankan","Nzérékoré")),
            new Country("GW","Guinea-Bissau", Arrays.asList("Bissau","Bafatá","Gabú","Cacheu","Bolama")),
            new Country("KE","Kenya", Arrays.asList("Nairobi","Mombasa","Nakuru","Naivasha","Kisumu")),
            new Country("LS","Lesotho", Arrays.asList("Maseru","Teyateyaneng","Mafeteng","Hlotse","Butha-Buthe")),
            new Country("LR","Liberia", Arrays.asList("Monrovia","Gbarnga","Buchanan","Ganta","Harper")),
            new Country("LY","Libya", Arrays.asList("Tripoli","Benghazi","Misrata","Sabha","Zuwara")),
            new Country("MG","Madagascar", Arrays.asList("Antananarivo","Toamasina","Antsirabe","Mahajanga","Fianarantsoa")),
            new Country("MW","Malawi", Arrays.asList("Lilongwe","Blantyre","Mzuzu","Zomba","Mangochi")),
            new Country("ML","Mali", Arrays.asList("Bamako","Timbuktu","Sikasso","Kayes","Mopti")),
            new Country("MR","Mauritania", Arrays.asList("Nouakchott","Nouadhibou","Atar","Rosso","Kaédi")),
            new Country("MU","Mauritius", Arrays.asList("Port Louis","Curepipe","Quatre Bornes","Flic-en-Flac","Grand Baie")),
            new Country("MA","Morocco", Arrays.asList("Marrakesh","Casablanca","Rabat","Fes","Tangier","Agadir","Chefchaouen")),
            new Country("MZ","Mozambique", Arrays.asList("Maputo","Beira","Nampula","Pemba","Inhambane")),
            new Country("NA","Namibia", Arrays.asList("Windhoek","Swakopmund","Walvis Bay","Lüderitz","Etosha")),
            new Country("NE","Niger", Arrays.asList("Niamey","Agadez","Zinder","Maradi","Tahoua")),
            new Country("NG","Nigeria", Arrays.asList("Lagos","Abuja","Ibadan","Port Harcourt","Enugu")),
            new Country("RW","Rwanda", Arrays.asList("Kigali","Huye","Musanze","Rubavu","Nyamata")),
            new Country("ST","São Tomé and Príncipe", Arrays.asList("São Tomé","Trindade","Neves","Santana","Guadalupe")),
            new Country("SN","Senegal", Arrays.asList("Dakar","Saint-Louis","Saly","Thiès","Ziguinchor")),
            new Country("SC","Seychelles", Arrays.asList("Victoria","Beau Vallon","Anse Royale","Praslin","La Digue")),
            new Country("SL","Sierra Leone", Arrays.asList("Freetown","Bo","Kenema","Koidu","Makeni")),
            new Country("SO","Somalia", Arrays.asList("Mogadishu","Hargeisa","Berbera","Kismayo","Baidoa")),
            new Country("ZA","South Africa", Arrays.asList("Cape Town","Johannesburg","Durban","Pretoria","Port Elizabeth","Stellenbosch")),
            new Country("SS","South Sudan", Arrays.asList("Juba","Wau","Malakal","Bor","Yei")),
            new Country("SD","Sudan", Arrays.asList("Khartoum","Omdurman","Port Sudan","Kassala","El Obeid")),
            new Country("TZ","Tanzania", Arrays.asList("Zanzibar City","Arusha","Dar es Salaam","Moshi","Dodoma","Nungwi")),
            new Country("TG","Togo", Arrays.asList("Lomé","Kpalimé","Sokodé","Kara","Atakpamé")),
            new Country("TN","Tunisia", Arrays.asList("Tunis","Sousse","Hammamet","Djerba","Monastir")),
            new Country("UG","Uganda", Arrays.asList("Kampala","Entebbe","Jinja","Mbarara","Gulu")),
            new Country("ZM","Zambia", Arrays.asList("Lusaka","Livingstone","Ndola","Kitwe","Chipata")),
            new Country("ZW","Zimbabwe", Arrays.asList("Harare","Bulawayo","Victoria Falls","Mutare","Gweru"))
    );}
}
